In [76]:
import pandas as pd

 School ranking - to isolate just the state and the overall ranking, to drop the index column

In [77]:
school_DF=pd.read_csv('./Data/school_ranking.csv')

Copy of original DF is made - so if there are mistakes, I can always go back to original.  Working copy is called 'working_schoolDF'

In [78]:
working_schoolDF=school_DF.copy()

iloc command used to isolate only the columns for state name and overall ranking

In [79]:
working_schoolDF=working_schoolDF.iloc[:,0:2]
display(working_schoolDF)

    RANK           State
0      1      New Jersey
1      2   New Hampshire
2      3     Connecticut
3      4         Vermont
4      5   Massachusetts
5      6        New York
6      7           Maine
7      8        Colorado
8      9    Pennsylvania
9     10        Virginia
10    11        Delaware
11    12        Maryland
12    13      Washington
13    14         Wyoming
14    15       Minnesota
15    16            Iowa
16    17    South Dakota
17    18            Ohio
18    19       Wisconsin
19    20        Illinois
20    21        Nebraska
21    22    Rhode Island
22    23         Indiana
23    24          Oregon
24    25    North Dakota
25    26        Missouri
26    27         Montana
27    28          Kansas
28    29        Michigan
29    30        Kentucky
30    31         Georgia
31    32        Arkansas
32    33           Idaho
33    34   West Virginia
34    35          Alaska
35    36          Hawaii
36    37            Utah
37    38           Texas
38    39     Mississippi
39    40      California
40    41       Tennessee
41    42         Florida
42    43  North Carolina
43    44        Oklahoma
44    45  South Carolina
45    46         Alabama
46    47      New Mexico
47    48          Nevada
48    49       Louisiana
49    50         Arizona